# Generated by Django 4.1.13 on 2024-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('1', 'kids'), ('2', 'teenagers'), ('3', 'adults')], default='1', max_length=1),
        ),
    ]
