# Generated by Django 4.1.13 on 2024-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=1990),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
