# Generated by Django 4.1.13 on 2024-07-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_author_alter_book_price_alter_book_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='status',
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
